### ISSUE TITLE
Expand processing.py to allow for punctuation, and clean up the code

### ISSUE THREAD

**Issue by Kronifer** [Kronifer/code-jam-10#4]
Expand the alphabet generated to include punctuation, such as `.,!?"'` and others if needed (please comment on this issue if you've claimed it and wish to add more). This should be achieved by adding these characters to the dictionary and then increasing the randint range. In addition to this, a cleanup of the code used to generate and read the encoded images is needed. This can be assigned to multiple people or split into multiple issues if needed.

**Comment by Today100** [comment]
I will take over this task.
